### ISSUE TITLE
[question]-[dependencies] - what does ^ ~ symbols mean?

### ISSUE THREAD

**Issue by shantanu301** [CodeKul/angular-weekend-23-march-2019-1030-1230#3]
"dependencies": {
    "canonical-path": "~0.0.2",
    "dependency-graph": "^0.7.0",
    "di": "0.0.1",
    "lodash": "^4.17.10",
    "objectdiff": "^1.1.0",
    "optimist": "~0.6.1",
    "q": "^1.5.1",
    "validate.js": "^0.12.0",
    "winston": "^2.1.1"
  }

**Comment by aniruddhha** [comment]
**_#copypaste_**
To keep the JavaScript ecosystem healthy, reliable, and secure, every time you make significant updates to an npm package you own, we recommend publishing a new version of the package with an updated version number in the package.json file that follows the semantic versioning spec. Following the semantic versioning spec helps other developers who depend on your code understand the extent of changes in a given version, and adjust their own code if necessary.  

For more details kindly follow the give link

https://docs.npmjs.com/about-semantic-versioning

**Comment by shantanu301** [comment]
thank you sir appreciate your quick reply
